[package]
name = "zheos"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[[bin]]
name = "zheos"
path = "src/main.rs"
# No libtest for aarch64-unknown-none-softfloat, and panic="abort" is
# incompatible with the default harness - so don't generate test/bench targets.
test = false
bench = false
