import { Doc, Frame, Box, Edge, Edges, Text } from "tldx";

export default function Diagram() {
  return (
    <Doc layout="col" gap="80">
      <Text size="l">v.push(i) reaches RAM in seven steps</Text>

      <Frame id="alloc-crate" name="alloc crate - ships with the compiler, knows nothing about you" layout="col" gap="50">
        <Box id="push" label={"1. Vec::push\nthe vector is full"} color="grey" />
        <Box id="grow" label={"2. RawVec::grow_one\npicks the new capacity, builds a Layout"} color="grey" />
        <Box id="oom" label={"raw_vec::handle_error\npanic: memory allocation of N bytes failed\nlands in your #[panic_handler]"} color="red" />
      </Frame>

      <Frame id="shims" name="generated by #[global_allocator] - no source of yours" layout="col" gap="30">
        <Box id="rrealloc" label={"3. __rust_realloc\nrebuilds the Layout, calls the method"} color="orange" />
        <Text size="s">plus __rust_alloc, __rust_dealloc, __rust_alloc_zeroed - the same door for Box::new and for drop</Text>
      </Frame>

      <Frame id="yours" name="src/heap.rs - the part you write" layout="col" gap="50">
        <Box id="realloc" label={"4. Heap::realloc - the trait's default body\nalloc the new block, copy, dealloc the old one"} color="blue" />
        <Box id="halloc" label={"5. Heap::alloc\nOption<NonNull<u8>> becomes *mut u8, None becomes null"} color="blue" />
        <Box id="wi" label={"SpinLock guard - from LOCK\nmask IRQ, then take the lock"} color="violet" />
        <Box id="cell" label={"6. SLAB\nround to a size class, pop a free slot"} color="violet" />
      </Frame>

      <Frame id="bumpf" name="the layers underneath - built before this skill" layout="col" gap="50">
        <Box id="balloc" label={"7. FRAMES\nonly when no slab has room: one page, order 0"} color="green" />
        <Box id="ram" label={"RAM inside board.memory\nmapped NORMAL by identity_map"} geo="ellipse" color="green" />
      </Frame>

      <Edges>{`
        push -> grow
        realloc -> halloc: twice, and dealloc in between
        halloc -> wi -> cell
        cell -> balloc: no partial slab
        balloc -> ram
      `}</Edges>

      <Edge from="rrealloc" to="realloc" fromSide="bottom-right" toSide="top-right" />
      <Edge from="grow" to="rrealloc" label={"old pointer, old size,\nalign, new size"} fromSide="bottom-right" toSide="top-right" />
      <Edge from="halloc" to="oom" color="red" dash="dashed" label="null comes back" fromSide="left" toSide="left" />
    </Doc>
  );
}
